# Generated by Django 4.2.2 on 2023-06-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobUrl', models.CharField(max_length=2000)),
                ('jobTitle', models.CharField(max_length=500)),
                ('jobLocation', models.CharField(max_length=50)),
                ('jobAttributes', models.CharField(max_length=500)),
                ('jobDescription', models.CharField(max_length=500)),
            ],
        ),
    ]
